interfaces:

 - name: Ethernet0/0
   description: Link to R1 configured by Ansible
   ipv4: 10.1.11.2/24
   ipv6: 2001:db8:acad:11::2/64
   link_local: fe80::11:2
   AS: "64513"
   mode: "L3"

 - name: Loopback 0
   description: Loopback 0 configured by Ansible
   ipv4: 209.165.201.1/25
   ipv6: 2001:db8:209:165:201::1/80
   link_local: fe80::209:1

eigrp:
  instances:
    - asn : '64512'
      mode: 'classic'
      rid: '11.11.11.11' 
      networks:
        - 10.1.11.0/24
        - 198.51.100.0/24