interfaces:

 - name: Ethernet0/0
   description: Link to R1 configured by Ansible
   ipv4: 10.1.32.2/24
   ipv6: 2001:db8:acad:32::2/64
   link_local: fe80::32:2
   mode: "L3"

 - name: Loopback 0
   description: Loopback 0 configured by Ansible
   ipv4: 198.51.100.1/25
   ipv6: 2001:db8:198:51:100::1/80
   link_local: fe80::198:1


eigrp:
  instances:
    - asn : '64514'
      mode: 'classic'
      rid: '22.22.22.22' 
      networks:
        - 10.1.32.0/24
