interfaces:
 - name: Ethernet0/0
   description: Link to R2 configured by Ansible
   ipv4: 10.1.12.1/24
   ipv6: 2001:db8:acad:12::1/64
   link_local: fe80::12:1

 - name: Ethernet0/1
   description: Link to D1 configured by Ansible
   ipv4: 10.1.11.1/24
   ipv6: 2001:db8:acad:11::1/64
   link_local: fe80::11:1
   AS: "64512"
   cdp: 'no'

 - name: Loopback 1
   description: Loopback 1 configured by Ansible
   ipv4: 10.1.1.1/24
   ipv6: 2001:db8:acad:1::1/64
   link_local: fe80::1:1

eigrp:
  instances:
    - asn: '64512'
      rid: '1.1.1.1' 
      mode: 'classic'
      redistribute: '64513'
      networks:
        - 10.1.11.0/24
    - asn : '64513'
      mode: 'named'
      rid: '1.1.1.1' 
      asname: 'AS_CISCO'
      redistribute: '64512'
      networks:
        - 10.1.1.0/24
        - 10.1.12.0/24
      #redistribute: static
      #stub: static
