interfaces:
 - name: Ethernet0/0
   description: Link to R1 configured by Ansible
   ipv4: 10.1.12.2/24
   ipv6: 2001:db8:acad:12::2/64
   link_local: fe80::12:2
   AS: "64513"

 - name: Ethernet0/1
   description: Link to R3 configured by Ansible
   ipv4: 10.1.23.2/24
   ipv6: 2001:db8:acad:23::2/64
   link_local: fe80::23:2
   AS: "64512"

eigrp:
  instances:
    - asn : '64513'
      mode: 'named'
      rid: '2.2.2.2' 
      asname: 'AS_CISCO'
      networks:
        - 10.1.23.0/24
        - 10.1.12.0/24
